# Site settings
title: 朝花夕拾
email: superfreazy@126.com
description: > # this means to ignore newlines until "baseurl:"
  梦里花落知多少，却道天凉好个秋;落红不是无情物，学海无涯苦作舟。
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://superfreazy.github.io" # the base hostname & protocol for your site

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'tag'


# Social account
# twitter:  username
# weibo:    ID
github:   superfreazy
# codepen:  username
# dribbble: username


# Comment
# disqus_shortname: discussion_shortname


# Google Analytics
# google_analytics: tracking_ID


# Build settings
markdown: kramdown
sass:
  style: compressed
gems:
  - jekyll-sitemap
